typography_spectrum: 0.29801722313277423
color:
  saturation: 0.6162231375928968
  brandStrength: 0.11198228062130511
  lightness: 0.8829646876547486
  brandColors:
    - '#96CA2D'
    - '#B5E655'
    - '#EDF7F2'
    - '#4BB5C1'
    - '#7FC6BC'
  rhythmicContrast: 0.5261221169494092
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4641577
analytics:
  twitter: null
  google: null
  facebook: null
author:
  name: Michael Gulden
  email: activeoahutours@gmail.com
  url: 'http://activeoahu.com'
name: laieactivities
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: About
    id: 17e7d97f-7775-4fda-ba4a-eb294419cad0
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Laie Activities
description: Tours and activities near you
purpose: []
